### ISSUE TITLE
Light theme + about

### ISSUE THREAD

**Issue by oscarmlage** [oscarmlage/oscarmlagecom#5]
It seems the yellow text with white background is not readable at all.

**Comment by oscarmlage** [comment]
![image](https://user-images.githubusercontent.com/98542/166804042-f9e68fa5-6e63-4563-8e5c-5172e833ca89.png)

**Comment by segundofdez** [comment]
Fix:  https://github.com/oscarmlage/oscarmlagecom/commit/74f7bd599ce5422bdc23803bb7a49b43ed185f8a

**Comment by oscarmlage** [comment]
Thanks @reidrac for noticing and @segundofdez for the lovely fix!.
